Not-Zorro/monster_shop_1908

app/controllers/users_controller.rb, app/controllers/welcome_controller.rb, app/views/layouts/application.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb, app/views/welcome/index.html.erb, config/routes.rb, spec/features/navigation_spec.rb
User story 1 Add links in the nav bar:
- Home (link, route, controller, and view added)
- Register (link, route, controller, and view added) (no forms yet)
- Login (link,route, controller, and view added) (no forms yet)
Feature tests in navigation_spec
=> Nav bar setup

app/controllers/users_controller.rb, app/views/users/new.html.erb, spec/features/users/new_spec.rb
Add test for incomplete form
Add flash message for failure
Refactor password_confirmation tag
=> User register flash

spec/features/users/new_spec.rb
Add test for unique emails.
Co-Authored-By: Alice Post <ap2322@users.noreply.github.com>
Co-Authored-By: David Lopez <Not-Zorro@users.noreply.github.com>
=> User email registration must be unique

app.json
Co-Authored-By: Brian Bower <BabsLabs@users.noreply.github.com>
Co-Authored-By: Alice Post <ap2322@users.noreply.github.com>
=> Add auto deploy

app/controllers/application_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, db/migrate/20191022210143_add_role_to_users.rb, db/schema.rb, spec/features/users/regular_user/user_nav_spec.rb, spec/models/item_spec.rb, spec/models/user_spec.rb
Add links to profile and logout  and remove links for login and register in navbar for registered user.
Add tests.
Add column for role in user database.
Update user model.
=> User navigation bar

app/controllers/application_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, spec/features/users/merchant/nav_bar_spec.rb, spec/features/users/regular_user/user_nav_spec.rb, spec/models/user_spec.rb
Add merchant employee and merchant admin tests.
Add enum roles for merchant employee and merchant admin.
Add current user methods for merchant employee and merchant admin.
Add Dashboard link to navbar if logged in as a merchant employee and merchant admin.
=> Merchant navigation bar

app/assets/stylesheets/application.css, app/controllers/application_controller.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/users/new.html.erb, spec/features/users/admin/nav_spec.rb, spec/models/user_spec.rb
Add tests, links, and methods for admin.
=> Admin navigation

app/controllers/admin/base_controller.rb, app/controllers/admin/dashboard_controller.rb, app/controllers/merchant/base_controller.rb, app/controllers/merchant/dashboard_controller.rb, app/controllers/users_controller.rb, config/routes.rb, spec/features/users/visitors/404_spec.rb
Add namespaced routes and 404 errors when a visitor tries to access those routes. Add test too.
=> Visitor path errors

app/controllers/users_controller.rb, spec/features/users/regular_user/404_spec.rb
Add test for regular user 404 errors. Refactor user controller show method to use the current user instead of finding them by id.
=> User nav restrictions

spec/features/users/merchant/404_spec.rb
Add test for merchant 404 errors.
Co-Authored-By: David Lopez <Not-Zorro@users.noreply.github.com>
=> Merchant Navigation Restrictions

app/controllers/cart_controller.rb, spec/features/users/admin/404_spec.rb
Spec added for admin page restrictions
Add before each for a check on admin for cart
=> Admin nav restrictions

app/controllers/sessions_controller.rb, app/views/sessions/new.html.erb, config/routes.rb, spec/features/users/login_spec.rb
Spec for logging in with different permissions
Add views for different roles
Add flash message for successful login and unsuccessful
Add session creation
=> User login

app/controllers/application_controller.rb, app/views/items/index.html.erb, spec/features/items/index_spec.rb
Add test to see if merchant and admin can see active items.
Add above_average_user? helper method.
Add logic to see if you are a merchant or admin and if so you can see inactive items.
=> Don't show inactive items unless you are a merchant or admin

app/views/users/show.html.erb, spec/features/users/show_spec.rb
User story 18
- Add test to Users feature to log in as a registered user (all types) and visit the profile page to see the profile info and a link to edit
- Update users#show view users/show.html.erb to include the user info (excluding password) and a link to edit it
=> User profile show

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb
- Swapped `<p>` for `<div>`
- Applied styling of `.topnav a` to `.topnav div`
- Did not apply hover so it doesn't look like a link
=> Update formatting of 'Logged in' to match links in nav without hover

app/controllers/users_controller.rb, app/views/users/show.html.erb, config/routes.rb
Refactor user show page and controller action 
Refactor namespaced routes
=> Changes with user show page

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit_password.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/users/password_spec.rb
Add spec for sad paths and happy paths for all users
Add routes and views for linking to MVC for updating a password
=> Update password 

app/views/cart/show.html.erb, spec/features/cart/show_spec.rb
Create prompt and links showing visitors to register or login when viewing cart. 
Create tests for visitors cart.
=> Register checkout

app/models/user.rb, app/views/users/show.html.erb, spec/features/users/show_spec.rb, spec/models/user_spec.rb
Display link on user's profile page to navigate to their orders
- Requires user instance method has_orders?
- Updates users/show.html.erb to add link to display if user has orders
- Feature and model test written and all tests passing
=> Users orders link

app/models/order.rb, app/views/profile/orders/index.html.erb, spec/features/cart/checkout_spec.rb, spec/features/users/orders/index_spec.rb, spec/models/order_spec.rb
User Story 25 displaying order information
Feature test written for users/orders/index to show information about all orders for a user
New instance methods to format created_at and updated_at resource attributes
New instance method to count the number of items in an order
Model test written for new instance methods on orders.
=> User orders index

app/controllers/profile/orders_controller.rb, app/models/item_order.rb, app/models/order.rb, app/views/profile/orders/show.html.erb, config/routes.rb, db/migrate/20191025234720_add_status_to_item_orders.rb, db/schema.rb, spec/features/users/orders/show_spec.rb, spec/models/item_orders_spec.rb, spec/models/order_spec.rb
Create column for status on item_orders and created functionality
Create method update method to change status
Added status to view and cancel button
=> Cancel order dg

app/controllers/merchant/dashboard_controller.rb, app/models/merchant.rb, app/models/merchant_user.rb, app/models/user.rb, app/views/merchant/dashboard/index.html.erb, db/migrate/20191026185824_create_merchant_users.rb, db/schema.rb, spec/features/users/merchant/show_spec.rb, spec/models/merchant_spec.rb, spec/models/merchant_user_spec.rb, spec/models/user_spec.rb
Feature test to add an employer's address to a merchant user and merchant admin's dashboard
Decided to set up many-to-many relationship between merchants and users with the logic that a user could have more than one job at different merchants
Model tests for many-to-many relationship, updated models, added merchant_users.rb model
Rails g migration to CreateMerchantUsers and add merchant_id and user_id references
Update merchant/dashboard/index eg '/merchant' to include merchant's employer's address info.
All tests passing
=> Merchant dashboard with Employer's address - User Story 29

app/controllers/merchant/orders_controller.rb, app/models/item.rb, app/models/merchant.rb, app/models/order.rb, app/views/merchant/dashboard/index.html.erb, app/views/merchant/orders/show.html.erb, config/routes.rb, spec/features/users/merchant/index_spec.rb, spec/features/users/merchant/orders/show_spec.rb, spec/models/item_spec.rb, spec/models/order_spec.rb
User Story 32 adding information about an order for a specific merchant to that merchant's order show page
- Feature and model tests written and passed 
- Instance methods added to remove logic from the view
- New route within namespace :merchant to /merchant/orders/:id
=> Merchant order show 32

app/models/order.rb, app/views/merchant/dashboard/index.html.erb, spec/features/users/merchant/index_spec.rb, spec/models/order_spec.rb
Add methods grand_total_for_merchant and item_count_for_merchant with corresponding tests
Ass method calls in the view
=> Merchant Dashboard Fix

app/controllers/merchant/items_controller.rb, app/models/item.rb, app/views/merchant/orders/show.html.erb, config/routes.rb, spec/features/users/merchant/orders/show_spec.rb, spec/models/item_spec.rb
Add test, view, route, and action logic to allow for a merchant to fulfill orders.
=> Merchant can fulfill partial orders

app/views/merchant/orders/show.html.erb, spec/features/users/merchant/orders/show_spec.rb
Added if functionality on order/merchant show page so that an order can not be fulfilled as well as testing.
=> Merchant failed ordered 34

app/controllers/merchant/items_controller.rb, app/views/merchant/items/index.html.erb, config/routes.rb, spec/features/users/merchant/items/index_spec.rb
Create functionality and feature testing for having a deactivate button on active items on merchant/items
=> Item deactivate 35

db/seeds.rb
Add relationship between merchants and their employees and admin for testing purposes.
Co-Authored-By: David Lopez <Not-Zorro@users.noreply.github.com>
Co-Authored-By: Alice Post <ap2322@users.noreply.github.com>
=> Add relationships between merchants and employees/admins

app/controllers/merchant/items_controller.rb, app/controllers/sessions_controller.rb, app/views/merchant/items/index.html.erb, spec/features/cart/checkout_spec.rb, spec/features/users/merchant/items/index_spec.rb
Add test and functionality for only merchant admins to be able to disable items
=> Deactivate button for only merchant admins

app/controllers/merchant/items_controller.rb, app/models/item.rb, app/views/merchant/items/index.html.erb, config/routes.rb, spec/features/users/merchant/items/index_spec.rb, spec/models/item_spec.rb
Add test for activating as only a merchant admin.
Add MVC for activating an item as a merchant admin
Add model method to return item status and add model test
=> Activate item

app/controllers/merchant/items_controller.rb, spec/features/users/merchant/items/edit_item_spec.rb
Update test and controller to re-fill in an item's information in the edit form.
All tests passing.
=> Repopulate edit 41

app/controllers/admin/users_controller.rb, app/models/user.rb, app/views/admin/users/index.html.erb, config/routes.rb, spec/features/users/admin/users/index_spec.rb, spec/models/user_spec.rb
Add the ability for an admin to visit a user index page that links to each users profile. Also shows user created date and user role.
All tests passing.
=> Admin user index

app/controllers/admin/users_controller.rb, app/views/admin/users/show.html.erb, config/routes.rb, spec/features/users/admin/users/index_spec.rb, spec/features/users/admin/users/show_spec.rb
Add MVC and spec for admin users show page
Remove comment and save_and_open_page in specific tests
=> Admin user show

app/views/admin/merchants/show.html.erb, spec/features/users/admin/merchants/index_spec.rb, spec/features/users/admin/merchants/show_spec.rb, spec/features/users/admin/users/show_spec.rb, spec/models/merchant_spec.rb
Add MVC and spec for admin merchant show page
Remove commented out sections of tests
=> Admin merchant show

app/controllers/admin/merchants_controller.rb, spec/features/users/admin/merchants/index_spec.rb
Add flash message to controller/admin/merchants_controller
=> Disable merchant 48

app/controllers/admin/merchants_controller.rb, spec/features/users/admin/merchants/index_spec.rb
Add disable and enable functionality and feature testing.
=> Disable merchant items 49 

app/models/item.rb, app/views/items/index.html.erb, spec/features/items/index_spec.rb, spec/models/item_spec.rb
Add the ability for the top 5 and bottom 5 most sold items to show in the Items Index view.
=> Items stats

app/controllers/admin/merchants_controller.rb, app/controllers/merchant/dashboard_controller.rb, app/controllers/profile/orders_controller.rb, app/controllers/users_controller.rb, app/views/merchant/dashboard/edit.html.erb, app/views/users/edit.html.erb
This changes any use of instance variables in the view where we could be using our application_controller methods in the view.
=> Application controller in view

db/seeds.rb
Add new merchants, items, merchant employees and admins, and an order to the seed file.
Co-Authored-By: David Lopez <Not-Zorro@users.noreply.github.com>
=> Seed file addons

app/views/admin/merchants/edit.html.erb, app/views/admin/merchants/new.html.erb, app/views/admin/merchants/show.html.erb, app/views/admin/users/index.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, app/views/merchant/dashboard/edit.html.erb, app/views/merchant/items/edit.html.erb, app/views/merchant/items/index.html.erb, app/views/merchant/items/new.html.erb, app/views/merchants/index.html.erb, app/views/merchants/show.html.erb, app/views/profile/orders/index.html.erb, app/views/profile/orders/new.html.erb, app/views/profile/orders/show.html.erb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, config/routes.rb
Create resources for routes. 
Add prefix paths to views. 
Pulled in previous pull request to fix merge conflicts.
=> Resources 

app/views/admin/dashboard/index.html.erb
This makes the link for the user name lead to that show page
=> Admin user link
